services:
  IdentityDB:
    image: postgres:latest
    container_name: iddb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DbPassword}
    ports:
      - "5432:5432"
    volumes:
      - idVolume:/var/lib/postgresql
  RabbitMQ:
    image: rabbitmq:4.0-management
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMq__User}
      RABBITMQ_PASS: ${RabbitMq__Pass}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitVolume:/var/lib/rabbitmq
  BlogDB:
    image: postgres:latest
    container_name: bgdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DbPassword}
    ports:
      - "5433:5432"
    volumes:
      - bgVolume:/var/lib/postgresql
volumes:
  idVolume:
  bgVolume:
  rabbitVolume:
    driver: local